import baseWorker from './worker.js';

const AI_STATE_KEY='state/latest';
const AI_MODEL_DEFAULT='gemini-2.5-flash';
const AI_BUILD='ML-AI-GEMINI-20260913-V3';
const AI_MIN_INTERVAL_MS=30*60*1000;
const NEWS_MIN_SAFE=50;

const MEMORY_VERSION='ML-MEMORY-V1';
const MEMORY_INTERVAL_MINUTES=15;
function isoParts(d=new Date()){const p=n=>String(n).padStart(2,'0');return{y:d.getUTCFullYear(),m:p(d.getUTCMonth()+1),day:p(d.getUTCDate()),h:p(d.getUTCHours()),min:p(d.getUTCMinutes()),date:d.toISOString().slice(0,10)}}
function compactMemoryState(state){const market=state?.market||{};const indices=Array.isArray(market.indices)?market.indices.map(x=>({name:x.name,ticker:x.ticker,price:x.price,previous:x.previous,changePct:x.changePct,rsi:x.rsi,ok:x.ok,evaluation:x.evaluation})):[];const crypto=Array.isArray(market.crypto)?market.crypto.map(x=>({symbol:x.symbol,price:x.price,change24h:x.change24h,ok:x.ok,source:x.source})):[];const news=Array.isArray(state?.news?.items)?state.news.items.slice(0,180).map(x=>({title:clean(x.title,220),description:clean(x.description||x.summary||'',500),date:clean(x.date,40),url:clean(x.url||x.link,500),source:clean(x.source,100),type:clean(x.type,40),cat:clean(x.cat,40),score:Number(x.score||0)})):[];return{version:MEMORY_VERSION,capturedAt:new Date().toISOString(),phase:state?.phase||null,market:{timestamp:market.timestamp||null,indices,crypto,institutionalData:market.institutionalData||null,socialData:market.socialData||null,onchainData:market.onchainData||null},news:{timestamp:state?.news?.timestamp||null,summary:state?.news?.summary||null,top:news},ai:state?.ai?{status:state.ai.status,model:state.ai.model,generatedAt:state.ai.generatedAt,headline:clean(state.ai.headline,300),regime:clean(state.ai.regime,120),commentary:clean(state.ai.commentary,3500),thesis:clean(state.ai.thesis,1800)}:null}};
async function archiveMemory(env){if(!env.ML_MEMORY)return{ok:false,error:'R2 memory binding missing'};const state=await readKV(env,AI_STATE_KEY);if(!state)return{ok:false,error:'state unavailable'};const now=new Date(),p=isoParts(now);if(now.getUTCMinutes()%MEMORY_INTERVAL_MINUTES!==0)return{ok:true,skipped:true};const snapshot=compactMemoryState(state),key=`snapshots/${p.y}/${p.m}/${p.day}/${p.h}-${p.min}.json`;await env.ML_MEMORY.put(key,JSON.stringify(snapshot),{httpMetadata:{contentType:'application/json'}});const newsKey=`news/${p.y}/${p.m}/${p.day}.json`;try{const existing=await env.ML_MEMORY.head(newsKey);if(!existing&&Array.isArray(state?.news?.items))await env.ML_MEMORY.put(newsKey,JSON.stringify({version:MEMORY_VERSION,archivedAt:new Date().toISOString(),news:state.news}),{httpMetadata:{contentType:'application/json'}})}catch{}return{ok:true,key,newsKey}};
async function memoryRecent(env,date){if(!env.ML_MEMORY)return{ok:false,error:'R2 memory binding missing'};const d=date||new Date().toISOString().slice(0,10),safe=/^\d{4}-\d{2}-\d{2}$/.test(d)?d:new Date().toISOString().slice(0,10),[y,m,day]=safe.split('-'),listed=await env.ML_MEMORY.list({prefix:`snapshots/${y}/${m}/${day}/`,limit:100});return{ok:true,date:safe,count:listed.objects.length,objects:listed.objects.map(o=>({key:o.key,size:o.size,uploaded:o.uploaded,etag:o.etag}))}}
async function memoryRead(env,key){if(!env.ML_MEMORY)return null;if(!/^snapshots\/\d{4}\/\d{2}\/\d{2}\/\d{2}-\d{2}\.json$/.test(key))return null;const obj=await env.ML_MEMORY.get(key);if(!obj)return null;return await obj.json()}


const clean=(v,max=700)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,max);
async function readKV(env,key){try{const v=await env.ML_KV.get(key);return v?JSON.parse(v):null}catch{return null}}
async function writeKV(env,key,value){try{await env.ML_KV.put(key,JSON.stringify(value))}catch{}}
function titleKey(v){return clean(v,220).toLowerCase().replace(/[^a-z0-9à-ÿ]+/gi,' ').trim()}

function selectNews(news){
 const items=Array.isArray(news?.items)?news.items:[];
 const now=Date.now(),seen=new Set();
 return items.map(item=>{const date=Date.parse(item.date||'')||0;const age=date?Math.max(0,(now-date)/3600000):999;const freshness=age<=6?5:age<=24?4:age<=72?2:0;const relevance=Math.min(3,Math.abs(Number(item.score||0)));const category=['macro','rates','central','geopolitics','commodities','crypto','finance','company'].includes(String(item.cat||item.type||'').toLowerCase())?2:0;return{item,date,rank:freshness+relevance+category}}).sort((a,b)=>b.rank-a.rank||b.date-a.date).filter(row=>{const k=titleKey(row.item.title);if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,180).map(({item})=>({category:clean(item.cat||item.type||'news',40),date:clean(item.date,40),title:clean(item.title,220),context:clean(item.description||item.summary||'',900),source:clean(item.source||item.feed||'',100)}));
}
function clusterNews(news){const buckets=new Map();for(const item of news){const words=titleKey(`${item.title} ${item.context}`).split(' ').filter(w=>w.length>=5).slice(0,12);const key=words.slice(0,4).sort().join('|')||titleKey(item.title).slice(0,80);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(item)}return [...buckets.values()].filter(Boolean).map(group=>({categories:[...new Set(group.map(x=>x.category))].slice(0,6),representative:group.slice(0,4).map(x=>({title:x.title,source:x.source,date:x.date})),context:clean(group.map(x=>`${x.title} — ${x.context}`).join(' '),1400)})).slice(0,45)}
function compactMarket(market){if(!market||typeof market!=='object')return{};const out={};for(const[k,v]of Object.entries(market)){if(Array.isArray(v))out[k]=v.slice(0,80).map(x=>{if(!x||typeof x!=='object')return x;const o={};for(const[a,b]of Object.entries(x)){if(['closes','history','timestamps','raw','data'].includes(a))continue;if(typeof b==='number')o[a]=Number(b.toFixed?.(3)??b);else if(typeof b==='string'||typeof b==='boolean')o[a]=clean(b,100)}return o});else if(v&&typeof v==='object'){out[k]={};for(const[a,b]of Object.entries(v)){if(['closes','history','timestamps','raw','data'].includes(a))continue;out[k][a]=typeof b==='number'?Number(b.toFixed?.(3)??b):clean(b,140)}}else if(v!=null)out[k]=v}return out}
function previousContext(state){const ai=state?.ai;if(!ai||ai.status==='fallback')return null;return{generatedAt:ai.generatedAt||null,headline:clean(ai.headline,220),commentary:clean(ai.commentary||'',3200),thesis:clean(ai.thesis,1200),summary:clean(ai.summary,2200),regime:clean(ai.regime,200)}}

function localFallback(context,reason='Gemini temporaneamente non disponibile'){
 const m=context.market||{},news=context.news||[],idx=Array.isArray(m.indices)?m.indices:[],crypto=Array.isArray(m.crypto)?m.crypto:[];
 const avg=idx.map(x=>Number(x.changePct)).filter(Number.isFinite);const ca=crypto.map(x=>Number(x.change24h)).filter(Number.isFinite);const ac=avg.length?avg.reduce((a,b)=>a+b,0)/avg.length:0;const cc=ca.length?ca.reduce((a,b)=>a+b,0)/ca.length:0;
 const dxy=idx.find(x=>/DXY/i.test(x.name||'')),us10=idx.find(x=>/US10Y/i.test(x.name||'')),vix=idx.find(x=>/VIX/i.test(x.name||'')),gold=idx.find(x=>/GOLD/i.test(x.name||'')),oil=idx.find(x=>/BRENT|WTI/i.test(x.name||''));
 const drivers=[];if(ac>0.25)drivers.push('l’azionario mantiene un’impostazione positiva');if(ac<-0.25)drivers.push('l’azionario mostra pressione');if(cc>0.8)drivers.push('la crypto conferma una maggiore propensione al rischio');if(cc<-0.8)drivers.push('la debolezza della crypto segnala una partecipazione al rischio meno convinta');if(dxy&&Number(dxy.changePct)<-0.3)drivers.push('la debolezza del dollaro offre sostegno agli asset rischiosi');if(dxy&&Number(dxy.changePct)>0.3)drivers.push('la forza del dollaro introduce un elemento di cautela');if(us10&&Number(us10.changePct)<-0.3)drivers.push('il calo dei rendimenti sostiene le valutazioni');if(us10&&Number(us10.changePct)>0.3)drivers.push('il rialzo dei rendimenti limita il potenziale degli asset sensibili ai tassi');if(gold&&Number(gold.changePct)>0.5)drivers.push('l’oro conserva una componente difensiva');if(oil&&Number(oil.changePct)>1)drivers.push('la forza dell’energia mantiene un rischio inflazionistico');if(vix&&Number(vix.changePct)>2)drivers.push('la volatilità segnala un aumento della cautela');
 const lead=drivers.slice(0,4).join(', ');const tone=ac>0.35||cc>1?'costruttivo':ac<-0.35||cc<-1?'prudente':'misto';
 const recent=news.slice(0,5).map(x=>x.title).filter(Boolean);const newsSentence=recent.length?` Sullo sfondo, gli sviluppi più recenti indicano che il mercato sta ancora incorporando nuovi catalizzatori, per cui la reazione dei prezzi resta importante per distinguere un movimento strutturale da uno temporaneo.`:'';
 return{enabled:true,status:'fallback',model:AI_MODEL_DEFAULT,build:AI_BUILD,generatedAt:new Date().toISOString(),headline:`Quadro di mercato ${tone}.`,regime:tone,commentary:`Il quadro di mercato appare ${tone}. ${lead?`La lettura è guidata soprattutto dal fatto che ${lead}.`:'I segnali disponibili non mostrano una direzione sufficientemente uniforme per parlare di una tendenza dominante.'}${newsSentence} ${recent.length?'La priorità resta capire quali degli sviluppi in corso abbiano la capacità di modificare aspettative su crescita, inflazione, liquidità e politica monetaria, perché è da queste variabili che può arrivare la prossima estensione del movimento.':''} ${vix&&Number(vix.changePct)>2?'L’aumento della volatilità invita comunque a non interpretare la forza dell’azionario come assenza di rischio. ':''}Nel breve periodo il quadro resta quindi da leggere attraverso la convergenza tra prezzo, tassi, dollaro e asset rischiosi: una conferma simultanea rafforzerebbe la direzione attuale, mentre una divergenza tra questi segnali sarebbe il principale elemento da monitorare.`,thesis:'Interpretazione locale costruita sui dati disponibili; utilizzata solo come protezione quando una nuova elaborazione Gemini non è possibile.',summary:'',bullish:'',bearish:'',watch:'',fallbackReason:clean(reason,180)};
}

async function callGemini(env,context){const key=env.GEMINI_API_KEY||env.GOOGLE_GEMINI_API_KEY;if(!key)return null;const model=env.GEMINI_MODEL||AI_MODEL_DEFAULT;const system=`Sei il motore Market Intelligence di Miracolo Lab. Devi produrre una lettura finanziaria realmente ragionata del quadro corrente. Leggi tutte le informazioni disponibili nel contesto e sintetizza gli eventi materialmente rilevanti, senza trasformare il risultato in un riepilogo di articoli.
Integra quando pertinenti azioni, crypto, commodities, obbligazioni e tassi, FX, volatilità, macroeconomia e geopolitica. Collega le variabili: crescita, inflazione, politica monetaria, rendimenti, dollaro, liquidità e propensione al rischio. Identifica la narrativa dominante, le conferme, le contraddizioni, i catalizzatori e i rischi. Usa i prezzi per verificare se il mercato sta davvero confermando ciò che emerge dalle notizie.
Non contare gli articoli. Non citare fonti, News Core, pipeline, metodologia, numero di articoli, score o punteggi. Non inventare informazioni. Scrivi in italiano naturale, professionale e diretto. Produci un unico commento di 2-4 paragrafi, abbastanza ricco da essere utile ma non prolisso. Non suddividere il testo per categorie. La conclusione deve indicare lo scenario generale di breve periodo e cosa potrebbe invalidarlo.`;
 const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:JSON.stringify(context)}]}],generationConfig:{temperature:.45,maxOutputTokens:1800,responseMimeType:'application/json',responseSchema:{type:'object',properties:{headline:{type:'string'},regime:{type:'string'},commentary:{type:'string'},thesis:{type:'string'}},required:['headline','regime','commentary','thesis']}}})});if(!response.ok)throw Error(`Gemini HTTP ${response.status}`);const data=await response.json();const text=data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';if(!text)throw Error('Gemini empty response');return JSON.parse(text)}

async function generateAI(env,state,force=false){const previous=state?.ai||null;const news=selectNews(state?.news||{});const context={asOf:new Date().toISOString(),market:compactMarket(state?.market||{}),news,eventClusters:clusterNews(news),previousAnalysis:previousContext(state)};const now=Date.now(),last=Date.parse(previous?.generatedAt||'')||0;if(news.length<NEWS_MIN_SAFE&&Array.isArray(state?.news?.items)&&state.news.items.length<NEWS_MIN_SAFE&&previous)return{...previous,status:'stale',build:AI_BUILD};if(!force&&previous?.status==='ok'&&now-last<AI_MIN_INTERVAL_MS)return{...previous,status:'cached',build:AI_BUILD};const key=env.GEMINI_API_KEY||env.GOOGLE_GEMINI_API_KEY;if(!key)return previous?.status==='ok'?{...previous,status:'cached',build:AI_BUILD}:{...localFallback(context,'GEMINI_API_KEY non configurata')};try{const result=await callGemini(env,context);return{enabled:true,status:'ok',model:env.GEMINI_MODEL||AI_MODEL_DEFAULT,build:AI_BUILD,generatedAt:new Date().toISOString(),...result}}catch(e){return previous?.status==='ok'?{...previous,status:'stale',build:AI_BUILD,lastError:clean(e.message||e,180)}:localFallback(context,e.message||e)}}
async function runAI(env,force=false){const state=await readKV(env,AI_STATE_KEY);if(!state)return null;const ai=await generateAI(env,state,force);if(ai?.status==='ok'||ai?.status==='fallback')await writeKV(env,AI_STATE_KEY,{...state,ai});else if(ai)await writeKV(env,AI_STATE_KEY,{...state,ai:{...(state.ai||{}),...ai}});return ai}
async function waitForBaseStateAndRunAI(env,previousTimestamp){const deadline=Date.now()+30000;while(Date.now()<deadline){const state=await readKV(env,AI_STATE_KEY);if(state?.timestamp&&state.timestamp!==previousTimestamp)return runAI(env);await scheduler.wait(1000)}return runAI(env)}
export default{async scheduled(event,env,ctx){const minute=new Date(event.scheduledTime||Date.now()).getUTCMinutes();const previous=minute%10===0?await readKV(env,AI_STATE_KEY):null;await baseWorker.scheduled(event,env,ctx);if(minute%10===0)ctx.waitUntil(waitForBaseStateAndRunAI(env,previous?.timestamp||null));if(minute%15===0)ctx.waitUntil((async()=>{await scheduler.wait(5000);const state=await readKV(env,AI_STATE_KEY);if(state)await archiveMemory(env)})())},async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==='/api/ai'){const state=await readKV(env,AI_STATE_KEY);return Response.json({ok:true,build:AI_BUILD,ai:state?.ai||null},{headers:{'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}})}if(url.pathname==='/api/memory/recent'){try{return Response.json(await memoryRecent(env,url.searchParams.get('date')),{headers:{'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}})}catch(e){return Response.json({ok:false,error:String(e.message||e)},{status:500,headers:{'Access-Control-Allow-Origin':'*'}})}}if(url.pathname==='/api/memory/snapshot'){try{const key=url.searchParams.get('key')||'';const data=await memoryRead(env,key);return data?Response.json({ok:true,data},{headers:{'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}}):Response.json({ok:false,error:'Snapshot not found'},{status:404,headers:{'Access-Control-Allow-Origin':'*'}})}catch(e){return Response.json({ok:false,error:String(e.message||e)},{status:500,headers:{'Access-Control-Allow-Origin':'*'}})}}return baseWorker.fetch(request,env,ctx)}};
