/* Miracolo Lab — Market Analysis UI */
const ME=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=(v)=>Number.isFinite(v)?new Intl.NumberFormat('it-IT',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):'—';
const pct=(v)=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(2)}%`:'—';
function marketCard(x){const good=x.changePct>0;return `<div class="market-card"><div class="market-name">${ME(x.name)}</div><div class="market-price">${euro(x.price)}</div><div class="market-change ${good?'up':'down'}">${pct(x.changePct)}</div></div>`}
function strategyBlock(s){if(!s)return '';if(s.mode==='WAIT')return `<div class="strategy wait"><div class="strategy-head">🛡️ STRATEGIA: ATTENDERE</div><p>${ME(s.reason)}</p><div class="strategy-rule">Capitale monitorato: €${Number(s.capital||2000).toLocaleString('it-IT')}</div></div>`;return `<div class="strategy"><div class="strategy-head">🎯 STRATEGIA PAPER TRADING — €${Number(s.capital).toLocaleString('it-IT')}</div><p>Il motore seleziona solo asset che superano i filtri di trend e momentum. Nessun ordine reale viene eseguito.</p><div class="strategy-grid">${s.positions.map(p=>`<div class="position"><div><b>${ME(p.symbol)}</b> · ${ME(p.name)}</div><div class="position-score">Score ${p.score}/100</div><div class="position-row"><span>Allocazione</span><b>€${p.allocation.toLocaleString('it-IT')}</b></div><div class="position-row"><span>Ingresso indicativo</span><b>${euro(p.entry)}</b></div><div class="position-row"><span>Stop tecnico</span><b>${euro(p.stop)}</b></div><div class="position-row"><span>Target 2R</span><b>${euro(p.target)}</b></div></div>`).join('')}</div><div class="strategy-rule">Liquidità residua: €${Number(s.cash||0).toLocaleString('it-IT')} · ${ME(s.rule)}</div></div>`}
function analysisRows(list){return list.slice().sort((a,b)=>(b.analysis?.score||0)-(a.analysis?.score||0)).map(x=>{const a=x.analysis||{};return `<tr><td><b>${ME(x.symbol)}</b><br><span>${ME(x.name)}</span></td><td>${euro(x.price)}</td><td class="${x.changePct>=0?'up':'down'}">${pct(x.changePct)}</td><td>${a.sma20?euro(a.sma20):'—'}</td><td>${a.sma50?euro(a.sma50):'—'}</td><td>${a.rsi?a.rsi.toFixed(1):'—'}</td><td><b class="action-${a.action?.toLowerCase()}">${ME(a.action||'—')}</b><br><small>${a.score||0}/100</small></td></tr>`}).join('')}
async function loadMarket(){const el=document.getElementById('market');if(!el)return;el.innerHTML='<div class="market-loading">Recupero quotazioni, indici e indicatori online…</div>';try{const r=await fetch('/api/market?ts='+Date.now(),{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'HTTP '+r.status);const regime=d.marketRegime||{};el.innerHTML=`<div class="market-head"><div><h2>🧠 Market Intelligence</h2><p>Il motore confronta indici globali, quotazioni, trend e momentum e propone una strategia <b>paper trading</b> per un capitale di €2.000.</p></div><button id="refreshMarket" class="primary">↻ Aggiorna mercato</button></div><div class="regime"><div><span>Regime</span><b class="${regime.riskOn?'up':'down'}">${regime.riskOn?'RISK ON':'RISK OFF'}</b></div><div><span>VIX</span><b>${regime.vix?.toFixed(2)||'—'}</b></div><div><span>Indici positivi</span><b>${regime.breadth??0}/${regime.total??0}</b></div><div><span>Ultimo aggiornamento</span><b>${new Date(d.timestamp).toLocaleTimeString('it-IT')}</b></div></div>${strategyBlock(d.strategy)}<section class="market-section"><h3>Indici globali</h3><div class="market-grid">${d.indices.map(marketCard).join('')}</div></section><section class="market-section"><h3>Macro e materie prime</h3><div class="market-grid">${d.macro.map(marketCard).join('')}</div></section><section class="market-section"><h3>Watchlist e segnali tecnici</h3><div class="table-wrap"><table><thead><tr><th>Asset</th><th>Prezzo</th><th>24h</th><th>SMA20</th><th>SMA50</th><th>RSI</th><th>Decisione</th></tr></thead><tbody>${analysisRows(d.watchlist)}</tbody></table></div></section><div class="market-disclaimer">Dati di mercato recuperati online tramite feed pubblici. I valori possono essere ritardati o non disponibili per alcuni strumenti. La strategia è esclusivamente paper trading e non esegue ordini.</div>`;document.getElementById('refreshMarket')?.addEventListener('click',loadMarket)}catch(e){el.innerHTML=`<div class="error"><b>Market Intelligence non disponibile</b><br>${ME(e.message)}<br><small>Il radar News/Social continua a funzionare indipendentemente.</small></div>`}}
window.loadMarket=loadMarket;
