/* Miracolo Lab Worker V16.0 — Market Monitor Layer */
const BUILD='ML-20260829-V16.0-MARKET-MONITOR';
const BUILD_TIME=new Date().toISOString();
const UA_BROWSER='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36';
const ASSETS={GOLD:{symbol:'GOLD',isin:'FR0013416716',name:'Amundi Physical Gold ETC',market:'Milan',yahoo:['GOLD.MI','AGOLD.MI']},SWDA:{symbol:'SWDA',isin:'IE00B4L5Y983',name:'iShares Core MSCI World UCITS ETF',market:'Milan',yahoo:['SWDA.MI']},XMME:{symbol:'XMME',isin:'IE00BTJRMP35',name:'Xtrackers MSCI Emerging Markets UCITS ETF',market:'Milan',yahoo:['XMME.MI']}};
const FEEDS=[{name:'CNBC Finance',type:'news',cat:'news',url:'https://www.cnbc.com/id/100003114/device/rss/rss.html'},{name:'MarketWatch Top Stories',type:'news',cat:'news',url:'https://feeds.marketwatch.com/marketwatch/topstories/'},{name:'Google News Finance',type:'news',cat:'news',url:'https://news.google.com/rss/search?q=stock+market+OR+finance+OR+nasdaq+OR+sp500+OR+earnings&hl=en-US&gl=US&ceid=US:en'},{name:'Google News Macro',type:'news',cat:'macro',url:'https://news.google.com/rss/search?q=inflation+OR+%22interest+rate%22+OR+%22federal+reserve%22+OR+%22bond+yield%22+OR+CPI+OR+GDP&hl=en-US&gl=US&ceid=US:en'},{name:'Google News Crypto',type:'news',cat:'crypto',url:'https://news.google.com/rss/search?q=bitcoin+OR+ethereum+OR+crypto+OR+solana+OR+defi+OR+altcoin&hl=en-US&gl=US&ceid=US:en'},{name:'CoinDesk Crypto',type:'news',cat:'crypto',url:'https://www.coindesk.com/arc/outboundfeeds/rss/'}];
const MARKET={S_P500:'^GSPC',NASDAQ100:'^NDX',DOW:'^DJI',VIX:'^VIX',RUSSELL2000:'^RUT',NIKKEI:'^N225',DAX:'^GDAXI',EUROSTOXX50:'^STOXX50E',DXY:'DX-Y.NYB',GOLD_FUTURES:'GC=F',BRENT:'BZ=F',WTI:'CL=F',COPPER:'HG=F'};
function strip(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/g,"'").replace(/\s+/g,' ').trim()}
function field(x,n){const m=x.match(new RegExp('<'+n+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+n+'>','i'));return m?strip(m[1]):''}
function linkField(x){let m=x.match(/<link[^>]*href=["']([^"']+)["'][^>]*>/i);if(m)return m[1];m=x.match(/<link[^>]*>([\s\S]*?)<\/link>/i);return m?strip(m[1]):''}
async function fetchTimeout(url,options={},ms=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal,redirect:'follow'})}finally{clearTimeout(timer)}}
function scoreItem(i){const t=(i.title+' '+i.description).toLowerCase();let s=1;if(/crash|collapse|recession|war|default|panic|surge|plunge|rate cut|rate hike|inflation|tariff|bank failure|liquidat/.test(t))s+=2;if(/bitcoin|ethereum|crypto|nasdaq|s&p|sp500|fed|ecb|oil|gold/.test(t))s+=1;if(/breaking|urgent|record|all-time high|all-time low/.test(t))s+=1;return Math.min(6,s)}
function parseXML(text,feed){const out=[],re=/<(?:item|entry)(?:\s[^>]*)?>[\s\S]*?<\/(?:item|entry)>/gi;let m;while((m=re.exec(text))){const x=m[0],title=field(x,'title'),description=field(x,'description')||field(x,'summary')||field(x,'content'),date=field(x,'pubDate')||field(x,'published')||field(x,'updated'),link=linkField(x);if(title&&link)out.push({title,description,date,link,source:feed.name,cat:feed.cat,kind:feed.type,score:scoreItem({title,description})})}return out}
async function fullScan(){const results=await Promise.all(FEEDS.map(async f=>{try{const r=await fetchTimeout(f.url,{headers:{'User-Agent':UA_BROWSER,Accept:'application/rss+xml, application/xml, text/xml, text/html;q=0.8'}},9000);if(!r.ok)throw Error('HTTP '+r.status);const items=parseXML(await r.text(),f);return{name:f.name,cat:f.cat,type:f.type,status:'ok',count:items.length,error:null,items}}catch(e){return{name:f.name,cat:f.cat,type:f.type,status:'error',count:0,error:String(e.message||e),items:[]}}}));const all=results.flatMap(x=>x.items||[]).sort((a,b)=>Number(b.score||0)-Number(a.score||0));return{ok:true,timestamp:new Date().toISOString(),summary:{workingSources:results.filter(x=>x.status==='ok').length,failedSources:results.filter(x=>x.status!=='ok').length,total:all.length,news:all.filter(x=>x.kind==='news').length,social:0,strong:all.filter(x=>Number(x.score||0)>=5).length},sources:results.map(({items,...s})=>s),top_signals:all.slice(0,80),signals:all.slice(0,120),blackSwan:{score:0,level:'LOW',triggers:[],active:false}}}
async function yahoo(sym){const r=await fetchTimeout('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(sym)+'?range=1d&interval=1m&includePrePost=false',{headers:{'User-Agent':UA_BROWSER,Accept:'application/json'}},7000);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json(),m=d.chart?.result?.[0]?.meta;if(!m)throw Error('No market data');const price=Number(m.regularMarketPrice??m.chartPreviousClose??0);if(!Number.isFinite(price)||price<=0)throw Error('Invalid/zero market price');const prev=Number(m.previousClose??m.chartPreviousClose??price);return{price,prevClose:prev,change:price-prev,changePct:prev?((price-prev)/prev)*100:0,currency:m.currency||'',exchange:m.exchangeName||''}}
async function coinGeckoCrypto(){const r=await fetchTimeout('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=eur&include_24hr_change=true',{headers:{Accept:'application/json'}},9000);if(!r.ok)throw Error('CoinGecko HTTP '+r.status);const d=await r.json();return[['bitcoin','BTC','Bitcoin'],['ethereum','ETH','Ethereum']].map(([id,symbol,name])=>({id,symbol,name,price:Number(d[id]?.eur||0),change24h:Number(d[id]?.eur_24h_change||0)}))}
async function coinbaseOne(symbol,name){const product=symbol==='BTC'?'BTC-EUR':'ETH-EUR';const r=await fetchTimeout('https://api.exchange.coinbase.com/products/'+product+'/ticker',{headers:{Accept:'application/json'}},9000);if(!r.ok)throw Error('Coinbase '+product+' HTTP '+r.status);const d=await r.json(),price=Number(d?.price||0);if(!Number.isFinite(price)||price<=0)throw Error('Coinbase '+product+' invalid price');return{id:product,symbol,name,price,change24h:null}}
async function getCrypto(){let coins=[];try{coins=await coinGeckoCrypto()}catch{}const out=[];for(const [symbol,name] of [['BTC','Bitcoin'],['ETH','Ethereum']]){let c=coins.find(x=>x.symbol===symbol&&x.price>0);if(c)out.push({...c,verified:true,source:'CoinGecko EUR spot'});else try{c=await coinbaseOne(symbol,name);out.push({...c,verified:true,source:'Coinbase EUR spot'})}catch(e){out.push({symbol,name,price:null,verified:false,error:String(e.message||e)})}}return{ok:out.every(x=>x.verified&&x.price>0),timestamp:new Date().toISOString(),coins:out}}
async function marketMonitor(){const rows=await Promise.all(Object.entries(MARKET).map(async([name,ticker])=>{try{const q=await yahoo(ticker);return{name,ticker,...q,verified:true}}catch(e){return{name,ticker,price:null,verified:false,error:String(e.message||e)}}}));let btc=null;try{btc=(await getCrypto()).coins}catch{}return{ok:rows.some(x=>x.verified)||!!btc,timestamp:new Date().toISOString(),indices:rows,crypto:btc||[],regime:deriveRegime(rows,btc||[])}}
function deriveRegime(rows,crypto){const g=n=>rows.find(x=>x.name===n)?.changePct;const v=g('VIX'),sp=g('S_P500'),nd=g('NASDAQ100'),gold=g('GOLD_FUTURES'),score=(sp>0?1:-1)+(nd>0?1:-1)+(v<0?1:-1)+(gold<0?1:0);return{score,label:score>=2?'RISK-ON':score<=-2?'RISK-OFF':'NEUTRALE',drivers:{sp500:sp??null,nasdaq100:nd??null,vix:v??null,gold:gold??null}}}
async function getPrices(symbolsStr){const requested=[...new Set((symbolsStr||'').split(',').map(s=>s.trim()).filter(Boolean))].slice(0,50),results=[];for(const original of requested){const key=String(original).toUpperCase(),meta=ASSETS[key];let q=null,lastError='';if(meta)for(const source of meta.yahoo){try{q=await yahoo(source);if(key==='XMME'&&(q.currency!=='EUR'||q.price<60||q.price>100))throw Error('XMME sanity check failed: '+q.price);if(key==='GOLD'&&(q.currency!=='EUR'||q.price<100||q.price>250))throw Error('GOLD sanity check failed: '+q.price);if(key==='SWDA'&&(q.currency!=='EUR'||q.price<80||q.price>180))throw Error('SWDA sanity check failed: '+q.price);break}catch(e){lastError=String(e.message||e);q=null}}else{try{q=await yahoo(original)}catch(e){lastError=String(e.message||e)}}results.push(q&&q.price>0?{symbol:meta?.symbol||original,isin:meta?.isin,name:meta?.name||original,price:q.price,prevClose:q.prevClose,change:q.change,changePct:q.changePct,currency:q.currency,exchange:q.exchange,verified:true,sourceTicker:meta?.yahoo?.[0]||original}:{symbol:meta?.symbol||original,isin:meta?.isin,name:meta?.name||original,price:null,verified:false,error:lastError||'No valid non-zero market price'})}return{ok:true,timestamp:new Date().toISOString(),prices:results}}
function json(data){return Response.json(data,{headers:{'Cache-Control':'no-store, max-age=0','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*'}})}
export default{async fetch(request,env){const u=new URL(request.url),p=u.pathname;if(request.method==='OPTIONS')return new Response(null,{headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,OPTIONS'}});if(p==='/version')return json({ok:true,live:true,build:BUILD,buildTime:BUILD_TIME,assets:ASSETS,market:MARKET,check:'NONZERO-GUARD'});if(p==='/api/health')return json({ok:true,service:'Miracolo Lab',build:BUILD,timestamp:new Date().toISOString()});if(p==='/api/full-scan'||p==='/api/news')return json(await fullScan());if(p==='/api/crypto')return json(await getCrypto());if(p==='/api/market-monitor')return json(await marketMonitor());if(p==='/api/prices')return json(await getPrices(u.searchParams.get('symbols')||''));if(p==='/api/market')return json(await getPrices(u.searchParams.get('symbols')||'^GSPC,^NDX,^DJI,^VIX,GC=F,GOLD,SWDA,XMME'));if(env?.ASSETS)return env.ASSETS.fetch(new Request(request));return new Response('Not found',{status:404})}};