/* Miracolo Lab V21.3 — batched source engine and expanded cached news. */
import current from './worker-v21-1.js';

const VERSION='21.3.0';
const CACHE_KEY=new Request('https://miracolo-lab.local/v21/news-cache');
const GDELT_CACHE=new Request('https://miracolo-lab.local/v21/gdelt-cache');
const GDELT_QUERIES=[
['GDELT Markets','news','stocks OR Nasdaq OR S&P500 OR Dow Jones'],
['GDELT Macro','macro','Federal Reserve OR ECB OR inflation OR interest rates OR Treasury'],
['GDELT Crypto','crypto','Bitcoin OR Ethereum OR crypto OR cryptocurrency OR Bitcoin ETF'],
['GDELT Commodities','commodities','gold OR oil OR crude OR copper OR natural gas'],
['GDELT Geopolitics','geopolitics','tariffs OR sanctions OR trade war OR geopolitics OR Ukraine OR Middle East'],
['GDELT Company','company','Nvidia OR semiconductor OR artificial intelligence OR Microsoft OR TSMC'],
['GDELT Social','social','domain:reddit.com (stocks OR investing OR wallstreetbets OR Bitcoin OR ethereum OR options)']
];
const DISABLED=new Set(['Reddit Stocks','Reddit Investing','Reddit WSB','Reddit Crypto','Reddit Bitcoin','Reddit Options','Reddit Value','Reddit Stocks Market','Reddit Day Trading','Eurostat News']);
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'}})}
async function read(k){try{const r=await caches.default.match(k);return r?r.json():null}catch{return null}}
async function write(k,v){try{await caches.default.put(k,json(v))}catch{}}
async function gdelt(q){const [name,type,query]=q,started=Date.now();try{const u='https://api.gdeltproject.org/api/v2/doc/doc?query='+encodeURIComponent(query)+'&mode=artlist&format=json&timespan=24h&maxrecords=250&sort=datedesc';const r=await fetch(u,{redirect:'follow',headers:{Accept:'application/json','User-Agent':'MiracoloLab/21.3'}});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();const raw=Array.isArray(d?.articles)?d.articles:[];const items=raw.map(x=>({title:String(x.title||'').trim(),description:'',date:x.seendate||'',url:x.url||'',link:x.url||'',source:name,type,cat:type,publisher:x.domain||'GDELT'})).filter(x=>x.title&&x.url);return{name,type,url:u,status:'ok',count:items.length,latencyMs:Date.now()-started,error:null,items}}catch(e){return{name,type,status:'error',count:0,latencyMs:Date.now()-started,error:String(e.message||e),items:[]}}}
async function refresh(){const states=[];for(const q of GDELT_QUERIES)states.push(await gdelt(q));await write(GDELT_CACHE,{timestamp:new Date().toISOString(),states,items:states.flatMap(s=>s.items)});return states}
function cleanBase(data){const items=(data.items||[]).filter(x=>!DISABLED.has(String(x?.source||'')));const sources=(data.sources||[]).map(s=>DISABLED.has(String(s?.name||''))?{...s,status:'disabled',count:0,error:s.name==='Eurostat News'?'SDMX endpoint, not RSS/Atom':'anonymous Reddit feed disabled; OAuth/API required'}:s);return {...data,items,sources}}
function merge(base,extra){base=cleanBase(base);const all=[...(base.items||[]),...(extra?.items||[])].filter(x=>x?.title);const key=x=>String(x.title).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();const items=[...new Map(all.map(x=>[key(x),x])).values()].filter(x=>x.title).slice(0,10000);const sources=[...(base.sources||[]),...((extra?.states||[]).map(({items,...s})=>s))];const groups={};for(const s of sources){const g=String(s.type||'other').toUpperCase();(groups[g]??=[]).push(s)}const newsTypes=new Set(['news','company','equity','macro','rates','central','commodities','fx','crypto','flows','volatility','geopolitics','regulatory']);return {...base,version:VERSION,items,sources,sourceGroups:groups,summary:{...(base.summary||{}),items:items.length,total:items.length,news:items.filter(x=>newsTypes.has(x.type)).length,social:items.filter(x=>x.type==='social').length,configured:sources.length,reachable:sources.filter(s=>s.status==='ok').length,failed:sources.filter(s=>s.status==='error').length,disabled:sources.filter(s=>s.status==='disabled').length,workingSources:sources.filter(s=>s.status==='ok').length}}}
export default {async scheduled(event,env,ctx){if(current.scheduled)ctx.waitUntil(current.scheduled(event,env,ctx));ctx.waitUntil(refresh())},async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/api/version')return json({version:VERSION,entrypoint:'worker-v21-2.js',baseline:'21.1.1',engine:'worker-v20+v21.1+v21.2+batched',refresh:'5m',reddit:false,x:Boolean(env?.X_BEARER_TOKEN),gdelt:true,aiHistory:true});if(u.pathname==='/api/source-diagnostics'){const c=await read(GDELT_CACHE);return json({version:VERSION,generatedAt:c?.timestamp||null,sources:c?.states||[]})}if(u.pathname==='/api/full-scan'){const upstream=await current.fetch(req,env,ctx),text=await upstream.text();let base;try{base=JSON.parse(text)}catch{return new Response(text,{status:upstream.status,headers:upstream.headers})}const c=await read(GDELT_CACHE);return json(merge(base,c),upstream.status)}return current.fetch(req,env,ctx)}};
